### ISSUE TITLE
Map design issue in index page

### ISSUE THREAD

**Issue by priyankatgit** [ornait/wedding_rudresh.github.io#5]
@ronchoqa 
After your last checking of index page there seems to be design issue at footer. Map is not showing in full width. It's because there is an extra div added under footer class div which have class container.
If you remove that div then it will show in full width.

Reason:
Media query is used on container class which is very to screen size to make all device compatible, and if you inspect element you can see container class has fix width applied. Here, we want to make it full scree.

Fix:
Remove container class div.

**Comment by ronchoqa** [comment]
Fixed.
